### ISSUE TITLE
gplog log level for file output

### ISSUE THREAD

**Issue by bxu-github** [greenplum-db/gp-common-go-libs#37]
I am a member of the gp-command-center team.
We am interested in the gplog ( https://github.com/greenplum-db/gp-common-go-libs/blob/master/gplog/gplog.go ) you provided in this repo, 
but I have a small problem before I can use it:
some project can print a lot of logs into file, but it will enable user to choose which level info they'd like to log to the logFile, 
For example, if user chose 'Warn', then he won’t see Logs under 'Warn' level, he can only see these logs:  
- 'Fatal'
- 'Error'
- 'Warn'

We regard this a common use case,  Could you pls provide this possibility?

**Comment by jmcatamney** [comment]
The gplog package has a `SetVerbosity` function to specify the logger's log level after it has been initialized.  To cause the logger to only display log messages with a level of Warning, Error, and Fatal, as in your example, you would call `gplog.SetVerbosity(gplog.LOGERROR)`.

Does that address your use case?

**Comment by bxu-github** [comment]
Thanks for your reply. 
We know this `SetVerbosity` func.
Our use case is if set log level to `Info`.  We do not want **log file**  contains `debug` level log. But now the log file contains `debug` level log actually.
We don’t know how to achieve this.

**Comment by jmcatamney** [comment]
Ah, I see what you mean now.  We currently default the logger to more verbose messages in the log file than at the terminal so that if a utility fails the user won't need to re-run it to get useful verbose output, but it shouldn't hurt to allow setting them separately as long as the logger still defaults to `INFO` for terminal output and `DEBUG` for log files.

I'll look into the cleanest way to make the change, given that existing utilities depend upon the current behavior.  Look for a PR to go up in the next few days.

**Comment by bxu-github** [comment]
It's very helpful. 
Thanks

**Comment by jimmyyih** [comment]
Closing issue.  Already fixed by https://github.com/greenplum-db/gp-common-go-libs/commit/aca9c3dc9103695d2b991c80eca40c1aeb67c38a.
