### ISSUE TITLE
cluster scopes: how can we include non-primary?

### ISSUE THREAD

**Issue by oliverralbertini** [greenplum-db/gp-common-go-libs#38]
Here on the UD team, for the `pxf` cli, we have a feature request for being able to sync our configs not just to segment hosts, but also the master standby. However, master standby doesn't come up in our query for segments since we are limiting to only primaries (no mirrors, no master standby).

@lavjain and I were exploring a possible solution. How about lifting the `WHERE s.role = 'p'` clause in the [GPDB query](https://github.com/greenplum-db/gp-common-go-libs/blob/afc498a415c4e67b08b3bd26fbaeef8e52f239a0/cluster/cluster.go#L325). Then the `SegConfig` struct could have an additional field `Primary` which could be a boolean.

Next we could either add a field to `Cluster` to indicate whether the user wants to include mirrors, or double the number of scopes, adding `_INCLUDE_MIRRORS` to the existing ones.

Any thoughts?

**Comment by jmcatamney** [comment]
Instead of adding a field to Cluster to tell it to retrieve mirror information, it would probably be best to add a flag to `GetSegmentConfiguration` to determine whether it returns mirrors or not (possibly defaulting to false using an optional argument, if we assume the vast majority of utilities are still only going to care about primaries).  Then SegConfig would need a new Role field, but I don't have strong opinions as to whether we make it a boolean or stick with the verbatim `'p'` or `'m'` string values retrieved from the database.

Regarding command execution, toggling whether mirrors are used at the cluster level rather than the command level only works if you're never going to want to execute some commands including mirrors and some excluding mirrors with the same `Cluster` object, since the command execution functions use all of the segments.  We can't guarantee that (I could easily see a `gpscp` implementation giving you a choice between with-mirrors or without-mirrors, for instance, or `gpupgrade` eventually allowing you to upgrade mirrors directly instead of having to drop mirrors, upgrade primaries, and recreate mirrors, and that's just looking at existing use cases), so a scope change would probably be better.

That said, doubling the scopes to 16 options would make things a bit unwieldy.  At this point it would make sense to split the scopes into toggles, so instead of passing one scope argument to a function you'd pass several, e.g. instead of `(cluster.ON_HOSTS_AND_MASTER_INCLUDE_MIRRORS)` you'd pass `(cluster.ON_HOSTS, cluster.INCLUDE_MASTER, cluster.INCLUDE_MIRRORS)`.  That would also make checks like "If we're executing on hosts, do X" easier, since you're just checking `if cluster.ON_HOSTS` instead of `if cluster.ON_HOSTS || CLUSTER.ON_HOSTS_AND_MASTER || cluster.ON_HOSTS_INCLUDE_MIRRORS || cluster.ON_HOSTS_AND_MASTER_INCLUDE_MIRRORS`.

I've been working on refactoring per-host execution works so it's not just a hack on top of per-segment execution in my 10% time, and that scoping change would be easier if done on top of that refactor.  If your feature request isn't super urgent, let me try to polish that up and get that PR'd in the next few days, and then I can follow it up with the use-mirrors refactor.

**Comment by oliverralbertini** [comment]
Thanks for the comment, @jmcatamney.

I agree, the scopes seems like the right place for this refactor, but is passing several toggle-like scopes going to mean changing the API of a method like `cluster.GenerateAndExecuteCommand()`? Or is it OK to add more scopes on the end in a variadic manner that won't break people's existing code, e.g. `GenerateAndExecuteCommand(verboseMsg string, execFunc func(contentID int) string, scopes ...int) *RemoteOutput`?

I don't know if it's possible using Go, but something I have seen in C is bit masking. User can provide something like `cluster.ON_SEGMENTS | cluster.INCLUDE_MIRRORS` and checking what's set becomes `(myFlag & cluster.INCLUDE_MIRRORS) != 0`.

**Comment by jmcatamney** [comment]
It looks like Go [does support](https://golang.org/ref/spec#Arithmetic_operators) bitwise operations, so  we could use those, we'd just have to specify the values manually instead of using an enum so the math works out.

We could either change it to require `OR`-ing together multiple values (which would be clearer and more extensible, but would be a breaking change) or set up the flags so that e.g. `cluster.ON_HOSTS_AND_MASTER` is defined to be equal to `cluster.ON_HOSTS | cluster.INCLUDE_MASTER` and so forth (which requires lots of variables but wouldn't change existing code).

Because the per-host execution change already involves an API change to un-hack-ify things, I'm inclined to go with the `OR`-ing approach and then utilities that consume `cluster` would only need to update their code once to accommodate both changes.
